### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by consigliere23** [ems-api/php-client#1]
Does not add a API Key in URL

**Comment by twisted1919** [comment]
It isn't suppose to add the API key in the url.

**Comment by consigliere23** [comment]
Where it is should add then?
When you append API key to API URL?

**Comment by twisted1919** [comment]
Please read the docs, they are very clear as to what you have to do.
https://api-docs.mailwizz.com/#introduction  
There's no place where you have to worry about adding the API key anywhere except when you init the API client itself, and that doesn't go in the url for sure.

**Comment by consigliere23** [comment]
Sorry, it works, adds a key to request in headers
