### ISSUE TITLE
api respond issue

### ISSUE THREAD

**Issue by masihfathi** [ems-api/php-client#2]
Hi
When Mw debug is enable, the api respond not work correctly.(i enable mw debug via init.php)
If it is reasonable remove log details with the respond body of this package. because package don't work, for example the get campaigns api body respond is like this.
```
EmsApi\Params {#848
  -_data: []
  -_readOnly: false
}
```

**Comment by twisted1919** [comment]
This is more of an issue with the way MailWizz outputs data when under debug mode, so if this is a concern for you, open a support ticket with MailWizz and ask for a way to avoid this for the API application.

**Comment by masihfathi** [comment]
Thanks i disable debug mode and it works as expected but i ask if its not expected behavior of api with debug mode.
