### ISSUE TITLE
Change API_KEY before making a new request is not working

### ISSUE THREAD

**Issue by plfiumi** [ems-api/php-client#3]
Hi, in my code I've a first require_once to setup, as is in your examples.

But I want to change the API_KEY after, so I request a new API_KEY to my user and then I do:

public static function config($instance) 
    {
		// get initial config and overwrite it each time
		$config = EmsApi\Config::getConfig();
		$config->setApiKey($instance['public_key']);
    }

This should be enough to set a new API_KEY, isn't it?

Is not working and I've no error arised this code (not even if I do a try catch wrapping it). Please help :).

**Comment by twisted1919** [comment]
`$config = EmsApi\Config::getConfig();` -- this is wrong, getConfig is not a static function, you can't obtain it like that.
You can keep a reference to your config object after you create it, and modify that on the fly as you need.
